[package]
name = "dt"
version = "9.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
axum = "0.8"
tower-http = { version = "0.6", features = ["cors", "fs"] }
prost = "0.14"
anyhow = "1.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite" ] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"
chrono = { version = "0.4", features = ["serde"] }
pbjson = "0.8"
connectrpc-axum = "*"

[features]
default = ["build_frontend"]
build_frontend = []

[build-dependencies]
connectrpc-axum-build = "*"

[dev-dependencies]
reqwest = { version = "0.12.5", default-features = false, features = ["blocking", "rustls-tls"] }
tempfile = "3.10.1"
