syntax = "proto3";

package dt.v1;

// Stores encrypted events from verifiable sources. The server is agnostic to the content of 'event_blob'
message Event {
  // Ed25519 Public Key of the user (32 bytes)
  bytes pub_key = 1;

  // Ed25519 Signature of the event_blob (64 bytes)
  bytes signature = 2;

  // The encrypted content (opaque to the server)
  bytes event_blob = 3;

  // Server-assigned timestamp (Unix epoch milliseconds)
  // NOTE: Ignored in PushRequest
  int64 server_timestamp_ms = 4;
}

// Incoming request with new events, and last received update timestamp
message SyncRequest {
  // Events to push to the server
  // NOTE: `Event.server_timestamp` will be overridden
  repeated Event new_events = 1;

  // Return events with server_timestamp > since_timestamp
  int64 since_timestamp_ms = 2;
}

// Outgoing response to client with events since previous sync
message SyncResponse {
  // Delta from the last sync
  repeated Event events = 1;

  // Current timestamp of the server
  int64 server_timestamp_ms = 2;
}

// Service for clients to synchronize events
service DtService {
  // Sync events from the log (and optionally push new ones).
  rpc Sync(SyncRequest) returns (SyncResponse);
}
