name: CI

on:
  push:
  pull_request:

jobs:
  buf:
    name: Buf Check
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'docs')
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.54.0"
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'
      - name: Check Formatting
        run: buf format --diff --exit-code

  frontend:
    name: Frontend CI
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'docs')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.54.0"
      - name: Install Dependencies
        run: npm ci
      - name: Generate Proto
        run: npm run generate
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build

  backend:
    name: Backend CI
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'docs')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.54.0"
      - name: Install Frontend Deps
        run: |
          cd ../frontend
          npm ci
          npm run generate
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      - name: Check Formatting
        run: cargo fmt --all -- --check
        continue-on-error: true
      - name: Lint
        run: cargo clippy -- -D warnings
        continue-on-error: true
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
